[DO-388] Add removal UI to multi select selected values
DripEmail/much-select-elm pull request #96
Opened 2022-01-12 22:01 UTC by sbone

2022-01-14 20:40 UTC, sbone commented
@jachin I have this functionality working! Going to connect w/ Jon on styling next week.

2022-01-18 20:58 UTC, jachin requested changes
I have a couple things that should probably be changed/fixed. Thank you for all the spelling fixes.

2022-01-18 20:58 UTC, jachin commented on src/Main.elm
> +import Ports exposing (addOptionsReceiver, allOptions, allowCustomOptionsReceiver, blurInput, customOptionHintReceiver, customOptionSelected, deselectOptionReceiver, disableChangedReceiver, errorMess
You could break up these across multiple lines.

2022-01-18 20:58 UTC, jachin commented on src/much-select.js
> +    } else if (name === "multi-select-single-removable-options") {
In your example you call the attribute `single-item-removal`... are you going with `multi-select-single-removable-options`?

2022-01-18 20:58 UTC, jachin commented on src/much-select.js
> +    } else if (name === "multi-select-single-removable-options") {
You probably want to add the attribute to the `observedAttributes` too.

2022-01-21 22:56 UTC, jachin approved these changes
Shoot, I'm sorry, I thought I approved this yesterday.

2022-02-04 19:48 UTC, merged